production:
  app: tastyplans
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-19856824-1"

staging:
  app: tastyplans-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
