production:
  app: ohmabel
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-19856824-1"

staging:
  app: ohmabel-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
